### ISSUE TITLE
Does queue target work?

### ISSUE THREAD

**Issue by fabiofalci** [GoogleCloudPlatform/appengine-modules-sample-java#18]
Having a queue targeting `shardecounter` module:

```
    <queue>
        <name>counter-queue</name>
        <rate>100/s</rate>
        <bucket-size>50</bucket-size>
        <mode>push</mode>
        <target>shardedcounter</target>
    </queue>
```

And then calling this code in the default module (`appengine-modules-guestbook`)

```
    Queue queue = QueueFactory.getQueue("counter-queue");
    queue.add(TaskOptions.Builder.withUrl("/worker").param("key", "testing"));
```

It doesn't go to `sharedcounter` module but it keeps trying the default module:

```
[INFO] INFO: Returning NOBODY because of SkipAdminCheck.
[INFO] Feb 24, 2016 2:50:38 PM com.google.appengine.api.taskqueue.dev.UrlFetchJob execute
[INFO] INFO: Web hook at http://127.0.0.1:8080/worker/ returned status code 404.  Rescheduling...
```

Is there any way to make this queue `target` configuration to work?

**Comment by ludoch** [comment]
Maybe the SDK support for queue and modules is not functional...
May I suggest you deploy the app modules in prod and report if this is the
same issue or if it works?

**Comment by fabiofalci** [comment]
It works in prod.
I was just wondering if I could replicate this queue communication in my local devserver.

**Comment by fabiofalci** [comment]
I'll try the other option described here https://cloud.google.com/appengine/docs/java/taskqueue/overview-push#Java_Task_execution

```
The module and version in which the handler runs is determined by:
The "Host" header parameter in the TaskOptions that you include in your call to the Queue.add() method.
The target directive in the queue.xml or queue.yaml file.
```

Setting the `host` header.

**Comment by ludoch** [comment]
make sure it is "Host" (we do not currently test for ignorecase, so host would not work).

**Comment by fabiofalci** [comment]
It did work using `Host`

```
    Queue queue = QueueFactory.getQueue("counter-queue");
    queue.add(TaskOptions.Builder
            .withUrl("/worker/")
            .param("key", "testing")
            .header("Host", ModulesServiceFactory.getModulesService().getVersionHostname("shardedcounter", null)));
```

So it seems `<target>shardedcounter</target>` is being ignored when devserver.

**Comment by fabiofalci** [comment]
Closing as is reported here
https://code.google.com/p/googleappengine/issues/detail?id=10457
